language: node_js

node_js:

  - "6.9"

  - "7.0"

before_script:

  - npm install -g yo bower grunt-cli gulp

  - npm install

env:

  - TEST_DIR=repasse-client

script: cd $TEST_DIR && npm install && bower install && npm test

notifications:

  email: false

after_script: cd $TEST_DIR && NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
